spring:
  banner:
    location: classpath:/banner/banner.txt 
  thymeleaf:    prefix: classpath:/view/ #se renombra de templates a view
    enable-spring-el-compiler: true
    cache: false
    
server:  error:    whitelabel:      enabled: false




    

    

    